// Isolated design prototype. All data and interactions stay in memory.
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const iconPaths = {
  grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
  home:'<path d="m3 10 9-7 9 7v10H3zM9 20v-7h6v7"/>',
  monitor:'<rect x="3" y="3" width="18" height="13" rx="2"/><path d="M8 21h8M12 16v5M6 11h3l2-4 3 6 2-3h2"/>',
  route:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="5" r="2"/><circle cx="5" cy="19" r="2"/><path d="M5 7v10M7 19h4a8 8 0 0 0 8-8V7"/>',
  settings:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2"/>',
  router:'<rect x="2" y="9" width="20" height="11" rx="2"/><path d="M6 9V3M18 9V3M6 14h.1M10 14h.1M15 16h4"/>',
  refresh:'<path d="M20 7a9 9 0 1 0 1 8M20 2v6h-6"/>',
  arrow:'<path d="m9 5 7 7-7 7"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6zM8 12l3 3 5-6"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name] || iconPaths.grid}</svg>`;
const groups = [['fleet','仪表台','grid'],['overview','系统概览','home'],['monitor','状态监控','monitor'],['host','主机设置','route'],['settings','面板设置','settings']];
const submenus = {
  monitor:[['interfaces','接口监控'],['terminals','终端监控'],['traffic','流量监控'],['services','网络服务'],['runtime','系统运行']],
  host:[['targets','目标库'],['routing','策略路由'],['access','访问控制'],['recognition','识别设置']],
  settings:[['devices','设备管理'],['collection','采集设置'],['appearance','界面设置'],['account','账号安全'],['maintenance','维护设置']]
};
const titles = Object.fromEntries([...groups,...Object.values(submenus).flat()].map(([key,title])=>[key,title]));
const state = {page:'overview',group:'overview',family:'全部',termSearch:'',visibility:'online',sort:1,detail:null,step:0,editing:false,ruleName:'工作设备分流',priority:100,enabled:true,subject:'all',ingress:true,targets:['GitHub','Docker'],v4:true,v6:false,wan:'pppoe-out1',gateway:'',dns:'1.1.1.1',failure:'strict',ack:false,targetFilter:'全部',dialog:'',layout:'double',trafficWindow:'1 小时'};
const terminalRows = [
 ['办公电脑','02:00:00:00:00:11','192.0.2.11','2001:db8::11',126,'1.24 Mbps','24.6 Mbps','2.18 GB','18.42 GB','在线','2天 08小时','工作设备'],
 ['家庭 NAS','02:00:00:00:00:20','192.0.2.20','2001:db8::20',84,'842 Kbps','8.32 Mbps','38.6 GB','126.8 GB','在线','6天 12小时','存储服务'],
 ['客厅电视','02:00:00:00:00:31','192.0.2.31','2001:db8::31',32,'46 Kbps','16.2 Mbps','286 MB','46.7 GB','在线','03小时 18分','影音设备'],
 ['移动设备','02:00:00:00:00:42','192.0.2.42','2001:db8::42',48,'124 Kbps','2.64 Mbps','842 MB','8.21 GB','在线','01小时 42分',''],
 ['实验主机','02:00:00:00:00:56','192.0.2.56','2001:db8::56',65,'2.08 Mbps','12.4 Mbps','8.24 GB','22.8 GB','在线','12小时 06分','测试环境'],
 ['平板电脑','02:00:00:00:00:67','192.0.2.67','2001:db8::67',18,'16 Kbps','824 Kbps','162 MB','1.24 GB','在线','00小时 28分',''],
 ['打印机','02:00:00:00:00:80','192.0.2.80','',0,'0 bps','0 bps','24 MB','68 MB','未活跃','—',''],
 ['备用电脑','02:00:00:00:00:92','192.0.2.92','',0,'0 bps','0 bps','1.2 GB','6.8 GB','离线','—','']
];
const rules = [
 {name:'工作设备分流',priority:100,source:'指定 2 台设备',sourceSub:'办公电脑、实验主机',targets:['GitHub','Docker','Cloudflare'],egress:'pppoe-out1',family:'IPv4 · IPv6',enabled:true},
 {name:'影音设备专线',priority:200,source:'指定 1 台设备',sourceSub:'客厅电视',targets:['YouTube'],egress:'ether3',family:'IPv4 · 下一跳 192.0.2.254',enabled:true},
 {name:'备用出口测试',priority:300,source:'LAN 全部',sourceSub:'接口列表',targets:['实验服务'],egress:'wireguard1',family:'IPv4',enabled:false}
];
function button(label,action,cls=''){const aria={refresh:"立即刷新",mobile:"打开或关闭导航",close:"关闭对话框",overview:"打开系统概览"}[action];return `<button class="${cls}" data-action="${action}" ${aria?`aria-label="${aria}"`:""}>${label}</button>`;}
function status(label='已启用',tone='good'){return `<span class="badge ${tone}">${tone==='good'?'<span class="status-dot"></span>':''}${label}</span>`;}
function tags(values){return `<div class="target-tags">${values.map(v=>`<span>${esc(v)}</span>`).join('')}</div>`;}
function kv(key,value){return `<div class="kv"><span>${key}</span><span>${value}</span></div>`;}
function pagination(count){return `<div class="table-footer"><span>共 ${count} 条</span><div class="pagination"><button disabled aria-label="上一页">‹</button><span>1 / 1</span><button disabled aria-label="下一页">›</button></div></div>`;}
function tabs(values,current,action){return `<div class="tabs" role="tablist">${values.map(v=>`<button role="tab" aria-selected="${v===current}" class="${v===current?'active':''}" data-action="${action}" data-value="${v}">${v}</button>`).join('')}</div>`;}
function showToast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.hidden=true,3800);}
function navigate(page){state.page=page;state.detail=null;state.group=Object.keys(submenus).find(key=>submenus[key].some(([id])=>id===page))||page;$('#app').classList.remove('mobile-open');render();}
function renderNav(){
 $('#app').classList.toggle('no-sub',!submenus[state.group]);
 $('#primary').innerHTML=groups.map(([id,title,i])=>`<button data-action="nav" data-value="${id}" class="${state.group===id?'active':''}" ${state.group===id?'aria-current="page"':''}>${icon(i)}${title}</button>`).join('');
 $('#secondary').innerHTML=submenus[state.group]?`<div class="nav-caption">${titles[state.group]}</div>`+submenus[state.group].map(([id,title])=>`<button data-action="nav" data-value="${id}" class="${state.page===id?'active':''}" ${state.page===id?'aria-current="page"':''}>${title}</button>`).join(''):'';
}
function render(){
 renderNav();
 let heading=`<h1>${titles[state.page]}</h1>`;
 if(state.page==='terminals'&&!state.detail) heading=tabs(['全部','IPv4','IPv6'],state.family,'family');
 let context=`<span class="device-context">主路由 · CHR</span><span class="sample-time">${status('示例状态正常')} </span>`;
 if(['overview','fleet','terminals'].includes(state.page))context+=`${state.page==='terminals'&&!state.detail?'<input class="search" id="terminal-search" aria-label="搜索终端" placeholder="备注 / 名称 / IP / MAC" value="'+esc(state.termSearch)+'">':''}${button(icon('refresh'),'refresh')}<select aria-label="自动刷新间隔" id="refresh"><option>5 秒</option><option>1 秒</option><option>3 秒</option><option>10 秒</option><option>停止刷新</option></select>`;
 $('#topbar').innerHTML=`<div class="row">${button('☰','mobile','mobile-nav')}${heading}</div><div class="context">${context}</div>`;
 const pages={overview:overviewPage,fleet:fleetPage,terminals:terminalPage,routing:routingPage,targets:targetsPage,access:accessPage,devices:devicesPage,appearance:appearancePage};
 $('#page').innerHTML=(pages[state.page]||placeholderPage)();
}
function chart(){
 const points=Array.from({length:61},(_,i)=>[50+i*11.6,140-Math.sin(i*.7)*20-Math.cos(i*.25)*28-(i>20&&i<34?42:0)]);
 const points2=points.map(([x,y],i)=>[x,183-(200-y)*.24-Math.sin(i*.9)*5]);
 const line=arr=>arr.map(p=>p.join(',')).join(' ');
 return `<svg class="chart" viewBox="0 0 780 238" preserveAspectRatio="none" role="img" aria-label="示例上行和下行速率趋势，横轴为时间，纵轴为 Mbps"><defs><linearGradient id="area-green" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7fc5a5" stop-opacity=".22"/><stop offset="1" stop-color="#7fc5a5" stop-opacity=".02"/></linearGradient></defs>${[40,80,120,160,200].map((y,i)=>`<line x1="50" x2="746" y1="${y}" y2="${y}"/><text x="4" y="${y+4}">${80-i*20}</text>`).join('')}<text x="4" y="17">Mbps</text><polygon points="50,200 ${line(points)} 746,200" fill="url(#area-green)"/><polyline points="${line(points)}" fill="none" stroke="var(--green)" stroke-width="2"/><polyline points="${line(points2)}" fill="none" stroke="var(--purple)" stroke-width="1.8"/>${['09:00','09:10','09:20','09:30','09:40','09:50','10:00'].map((v,i)=>`<text x="${50+i*116}" y="225" text-anchor="${i===6?'end':i===0?'start':'middle'}">${state.trafficWindow==='24 小时'?`${String(i*4).padStart(2,'0')}:00`:v}</text>`).join('')}</svg>`;
}
function overviewPage(){return `
 <section class="panel device-banner"><div class="identity"><div class="device-glyph">${icon('router')}</div><div><strong>主路由</strong><div class="sub">MikroTik CHR · RouterOS 7.22.3</div><div class="sub">运行 6 天 12 小时　${status('正常')}</div></div></div><div class="metric"><div class="metric-label">终端数量</div><div class="metric-value"><b>8</b><small>台</small></div><span class="sub">6 在线 · 1 未活跃 · 1 离线</span></div><div class="metric purple"><div class="metric-label">活动连接</div><div class="metric-value"><b>373</b><small>条</small></div><span class="sub">248 TCP · 125 UDP</span></div><div class="metric amber"><div class="metric-label">资源使用</div><div class="metric-value"><span class="resource-reading"><b>8</b><small>% CPU</small></span><span class="resource-reading"><b>28</b><small>% 内存</small></span></div><span class="sub">1.12 GB / 4.00 GB</span></div></section>
 <div class="dashboard-grid"><div class="stack"><section class="panel"><div class="panel-head"><h2>接口信息</h2><select aria-label="选择 WAN 接口" id="wan-summary"><option>pppoe-out1</option><option>ether3</option></select></div><div class="panel-body">${kv('运行状态',status('运行中'))}${kv('接口类型','PPPoE Client')}${kv('IPv4 地址','198.51.100.18')}${kv('IPv6 地址','2001:db8:1::18')}<div class="section-divider"></div><div class="between"><div><span class="sub">↑ 上行速率</span><div class="rate up">4.45 <small>Mbps</small></div></div><div><span class="sub">↓ 下行速率</span><div class="rate down">65.0 <small>Mbps</small></div></div></div><div class="section-divider"></div>${kv('累计上行','68.4 GB')}${kv('累计下行','224.1 GB')}${button('查看全部接口 '+icon('arrow'),'interfaces','link')}</div></section><section class="panel"><div class="panel-head"><h2>设备信息</h2></div><div class="panel-body">${kv('设备地址','192.0.2.1')}${kv('架构','x86_64')}${kv('处理器','4 核心')}${kv('系统时间','2026-09-05 10:00')}${button('资源监控 '+icon('arrow'),'runtime','link')}</div></section></div><div class="stack"><section class="panel"><div class="panel-head"><h2>上下行速率</h2><div class="segmented" aria-label="流量时间范围">${['1 小时','24 小时'].map(v=>`<button class="${state.trafficWindow===v?'active':''}" data-action="traffic-window" data-value="${v}">${v}</button>`).join('')}</div></div><div class="panel-body"><div class="legend"><span><i style="background:var(--green)"></i>下行</span><span><i style="background:var(--purple)"></i>上行</span></div>${chart()}<div class="chart-footer"><span>当前下行 <b>65.0 Mbps</b></span><span>峰值下行 <b>86.4 Mbps</b></span><span>当前上行 <b>4.45 Mbps</b></span></div></div></section><div class="halves"><section class="panel"><div class="panel-head"><h2>CPU 使用率</h2>${button('查看详情','runtime','link')}</div><div class="panel-body"><div class="rate">8 <small>%</small></div><div class="progress"><span style="width:8%"></span></div><span class="sub">4 核心 · 负载正常</span></div></section><section class="panel"><div class="panel-head"><h2>内存使用率</h2>${button('查看详情','runtime','link')}</div><div class="panel-body"><div class="rate">28 <small>%</small></div><div class="progress"><span style="width:28%;background:var(--purple)"></span></div><span class="sub">已用 1.12 GB / 总计 4.00 GB</span></div></section></div><section class="panel"><div class="panel-head"><h2>终端流量</h2>${button('全部终端 '+icon('arrow'),'terminals','link')}</div><table><thead><tr><th>设备</th><th>上行速率</th><th>下行速率</th><th>连接数</th></tr></thead><tbody>${terminalRows.slice(0,3).map(t=>`<tr><td>${button(t[0],'detail','link')}</td><td>${t[5]}</td><td>${t[6]}</td><td>${t[4]}</td></tr>`).join('')}</tbody></table></section></div></div>`;}
function fleetPage(){return `<div class="fleet-metrics">${[['全部设备','2'],['在线设备','2'],['离线设备','0'],['告警设备','0']].map(([name,num])=>`<div class="metric"><div class="metric-label">${name}</div><div class="metric-value"><b>${num}</b><small>台</small></div></div>`).join('')}</div><section class="panel"><div class="panel-head"><h2>设备运行列表</h2><input class="search" aria-label="搜索示例设备" placeholder="搜索设备名称、型号、版本或 IP" id="fleet-search"></div><div class="table-wrap"><table><thead><tr>${['设备信息','CPU','内存','流量速率','终端数量','连接数量','运行时间',''].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${['主路由','实验路由'].map((name,i)=>`<tr data-fleet-name="${name}"><td><strong>${name}</strong><span class="sub">${i?'RB5009':'CHR'} · 192.0.2.${i+1}</span>${status('正常')}</td><td>${button(i?'4%':'8%','runtime','link')}</td><td>${button(i?'18%':'28%','runtime','link')}</td><td><span class="up">↑ ${i?'286 Kbps':'4.45 Mbps'}</span><span class="sub down">↓ ${i?'1.2 Mbps':'65.0 Mbps'}</span></td><td>${button(i?'2 在线':'6 在线 · 1 未活跃 · 1 离线','terminals','link')}</td><td>${button(i?'42':'373','terminals','link')}</td><td>6天 12小时<span class="sub">更新于刚刚</span></td><td>${button(icon('arrow'),'overview')}</td></tr>`).join('')}</tbody></table></div>${pagination(2)}</section>`;}
function terminalPage(){
 if(state.detail)return detailPage();
 const rows=terminalRows.filter(r=>(state.visibility==='all'||(state.visibility==='online'?r[9]==='在线':r[9]!=='在线'))&&(state.family!=='IPv6'||r[3])&&r.join(' ').toLowerCase().includes(state.termSearch.toLowerCase())).sort((a,b)=>(Number(a[2].split('.').pop())-Number(b[2].split('.').pop()))*state.sort);
 return `<div class="summary-line"><span>终端总数<b>8</b></span><span>在线<b>6</b></span><span>未活跃<b>1</b></span><span>离线<b>1</b></span><span>连接数<b>373</b></span></div><section class="panel"><div class="table-wrap"><table class="terminal-table"><thead><tr><th>设备名称</th><th>${button('IP '+(state.sort===1?'↑':'↓'),'sort-ip')}</th><th>连接数</th><th>上行速率</th><th>下行速率</th><th>累计上行</th><th>累计下行</th><th><select id="online-filter" aria-label="筛选在线状态"><option value="online" ${state.visibility==='online'?'selected':''}>在线状态 ▾</option><option value="all" ${state.visibility==='all'?'selected':''}>全部设备</option><option value="offline" ${state.visibility==='offline'?'selected':''}>非在线设备</option></select></th><th>在线时长</th><th>备注</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="link name" data-action="detail" data-value="${r[0]}"><strong>${r[0]}</strong><span class="sub">${r[1]}</span></button></td><td><button class="link name" data-action="detail" data-value="${r[0]}">${state.family==='IPv6'?r[3]:r[2]}${state.family==='全部'&&r[3]?`<span class="sub">${r[3]}</span>`:''}</button></td>${r.slice(4,9).map(x=>`<td>${x}</td>`).join('')}<td>${status(r[9],r[9]==='在线'?'good':'neutral')}</td><td>${r[10]}</td><td>${r[11]||'—'}</td><td><div class="actions"><button class="link" data-action="remark" data-value="${r[0]}">编辑</button></div></td></tr>`).join('')||'<tr><td colspan="11" class="empty">没有符合当前筛选条件的终端</td></tr>'}</tbody></table></div>${pagination(rows.length)}</section>`;
}
function detailPage(){let r=terminalRows.find(t=>t[0]===state.detail)||terminalRows[0];return `<section class="panel"><div class="detail-info"><strong>${r[0]}</strong><span>${r[2]}</span><span class="muted">${r[1]}</span>${status(r[9])}<span class="muted">${r[4]} 条连接</span><span class="spacer"></span>${button('返回列表','back-terminals')}</div><div style="padding:0 20px;border-block:1px solid var(--line)">${tabs(['连接详情','应用统计','流量历史'],'连接详情','detail-tab')}</div><div class="table-wrap"><table style="min-width:1500px"><thead><tr>${['IP版本','应用','协议','源 IP','源端口','目标地址','路由表','下一跳网关','物理出口','上行速率','下行速率','累计上行','累计下行','连接时长'].map(x=>`<th>${x} ▾</th>`).join('')}</tr></thead><tbody>${['GitHub','Cloudflare','Docker','DNS'].map((a,i)=>`<tr><td><span class="badge">IPv4</span></td><td>${a}</td><td>${i===3?'UDP':'TCP'}</td><td>${r[2]}</td><td>${52010+i}</td><td>198.51.100.${30+i}:${i===3?'53':'443'}</td><td>work-route</td><td>192.0.2.254</td><td>pppoe-out1</td><td>12 Kbps</td><td>824 Kbps</td><td>242 KB</td><td>6.8 MB</td><td>00:12:24</td></tr>`).join('')}</tbody></table></div></section>`;}
function routingPage(){return `<div class="between page-heading"><div class="muted" style="font-size:13px">将来源、访问目标和出口组合成策略，应用前可审阅变更计划。</div>${button(icon('plus')+' 新增策略','new-rule','primary')}</div><section class="panel"><div class="table-wrap"><table style="min-width:930px"><thead><tr>${['名称','来源','目标','出口','状态','操作'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rules.map((r,i)=>`<tr><td><strong>${esc(r.name)}</strong><span class="sub">优先级 ${r.priority}</span></td><td>${r.source}<span class="sub">${r.sourceSub}</span></td><td>${tags(r.targets)}</td><td>${r.egress}<span class="sub">${r.family}</span></td><td>${status(r.enabled?'已启用':'已停用',r.enabled?'good':'neutral')}</td><td><div class="actions"><button class="link" data-action="toggle-rule" data-value="${i}">${r.enabled?'停用':'启用'}</button><button class="link" data-action="edit-rule" data-value="${i}">编辑</button><button class="link danger" data-action="delete-rule" data-value="${i}">删除</button></div></td></tr>`).join('')}</tbody></table></div>${pagination(rules.length)}</section>`;}
function targetsPage(){const rows=[['开发服务域名','域名','手动内容','12 条','2 条策略'],['常用应用 IP','IP','URL 订阅','168 条','1 条策略'],['实验服务','域名','上传文件','8 条','未使用']].filter(r=>state.targetFilter==='全部'||r[1]===state.targetFilter);return `<div class="between page-heading">${tabs(['全部','域名','IP'],state.targetFilter,'target-filter')}${button(icon('plus')+' 新增目标列表','new-target','primary')}</div><section class="panel"><div class="table-wrap"><table><thead><tr>${['目标列表','类型','来源','内容','使用中','状态','操作'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${r[0]}</strong></td><td><span class="badge neutral">${r[1]}</span></td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${status('就绪')}</td><td><div class="actions">${button('编辑','new-target','link')}${r[2]==='URL 订阅'?button('刷新','demo-refresh','link'):''}<button class="link danger" data-action="demo-delete" ${r[4]!=='未使用'?'disabled title="使用中的目标列表不能删除"':''}>删除</button></div></td></tr>`).join('')}</tbody></table></div>${pagination(rows.length)}</section><div class="notice" style="margin-top:18px">应用规则仍在策略向导的“访问目标”中选择；目标库继续管理可复用的手动、订阅和上传列表。</div>`;}
function accessPage(){return `<div class="between page-heading"><span class="muted">管理指定设备对互联网或目标列表的访问。</span>${button(icon('plus')+' 新增规则','new-access','primary')}</div><section class="panel"><div class="table-wrap"><table><thead><tr>${['规则','来源设备','访问目标','时间','状态','操作'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody><tr><td><strong>访客设备访问限制</strong><span class="sub">拒绝访问</span></td><td>指定 1 台设备<span class="sub">移动设备</span></td><td>目标列表<span class="sub">实验服务</span></td><td>始终<span class="sub">指定时间：即将支持</span></td><td>${status()}</td><td><div class="actions">${button('停用','demo-toggle','link')}${button('编辑','new-access','link')}${button('删除','demo-delete','link danger')}</div></td></tr></tbody></table></div>${pagination(1)}</section>`;}
function formRow(label,control,hint=''){return `<div class="form-row"><label>${label}</label><div>${control}${hint?`<span class="field-help">${hint}</span>`:''}</div></div>`;}
function devicesPage(){return `<div class="settings-grid"><section class="panel" style="align-self:start"><div class="panel-head"><h2>设备</h2>${button('+','demo-add-device')}</div><div class="settings-item active"><strong>主路由</strong><span class="sub">192.0.2.1　${status('正常')}</span></div><div class="settings-item"><strong>实验路由</strong><span class="sub">192.0.2.2　${status('正常')}</span></div></section><section class="panel"><div class="form"><div class="form-section"><div class="between"><h3>主路由</h3>${status('连接正常')}</div>${formRow('设备名称','<input aria-label="设备名称" value="主路由">')}${formRow('RouterOS 地址','<input aria-label="RouterOS 地址" value="192.0.2.1">')}${formRow('连接方式','<select aria-label="连接方式"><option>HTTPS · REST API</option><option>HTTP · REST API</option></select>')}${formRow('启用设备','<label class="check"><input type="checkbox" checked>启用数据采集</label>')}</div><div class="form-section"><h3>认证凭据</h3>${formRow('用户名','<input aria-label="用户名" placeholder="RouterOS 用户名">')}${formRow('密码','<input aria-label="密码" type="password" placeholder="留空保持现有密码">')}</div><div class="form-section"><h3>采集范围</h3>${formRow('WAN 接口','<input aria-label="WAN 接口" value="pppoe-out1, ether3">')}${formRow('LAN 接口列表','<input aria-label="LAN 接口列表" value="LAN">')}<details class="advanced"><summary>手动范围与高级连接设置</summary><div>${formRow('本地网段','<input aria-label="本地网段" value="192.0.2.0/24">')}<p class="field-help">完整字段在正式迁移时按现有设备编辑器保留，此处展示表单视觉。</p></div></details></div><div class="form-actions"><span class="spacer"></span>${button('测试连接','demo-connection')}${button('保存设备','demo-save','primary')}</div></div></section></div>`;}
function appearancePage(){return `<section class="panel form"><div class="form-section"><h3>外观</h3>${formRow('主题','<div class="choice-cards"><label class="choice-card"><input type="radio" name="appearance" value="light" '+(document.documentElement.dataset.theme!=='dark'?'checked':'')+'><span>明亮<span class="sub">白色界面 · 浅蓝强调</span></span></label><label class="choice-card"><input type="radio" name="appearance" value="dark" '+(document.documentElement.dataset.theme==='dark'?'checked':'')+'><span>深色<span class="sub">深蓝灰界面 · 柔和对比</span></span></label></div>')}${formRow('导航布局','<span class="muted">使用顶部“导航布局”切换比较。这是方案比较工具，不是新增的产品设置。</span>')}</div><div class="form-section"><h3>刷新偏好</h3>${formRow('监控刷新','<select aria-label="监控刷新"><option>5 秒</option><option>1 秒</option><option>3 秒</option><option>10 秒</option><option>停止刷新</option></select>')}</div><div class="form-actions">${button('保存偏好','demo-save','primary')}</div></section>`;}
function placeholderPage(){return `<section class="panel preview-placeholder"><div class="panel-head"><h2>${titles[state.page]}</h2></div><div class="panel-body"><p>此入口保留在完整迁移清单中，本轮未制作该页面的交互设计稿。当前可评审系统概览、仪表台、终端监控、策略路由、目标库、访问控制、设备管理和界面设置。</p>${button('查看策略路由与向导','routing','primary')}</div></section>`;}
function closeDialog(){ $('#editor').close();state.dialog=''; }
function dialogFrame(title,content,footer,subtitle='仅演示交互，不会保存或下发设备配置'){return `<div class="dialog-head"><div><h2>${title}</h2><p class="sub">${subtitle}</p></div>${button('×','close')}</div>${content}<div class="dialog-footer"><span class="muted">视觉方案 · 示例数据</span><div class="row">${footer}</div></div>`;}
function openDialog(){if(!$('#editor').open)$('#editor').showModal();}
function ruleWizard(){
 state.dialog='rule';
 const names=['策略与来源','访问目标','出口设置','预览并应用'];
 let content=`<div class="steps">${names.map((name,i)=>`${i?'<span class="step-line"></span>':''}<button class="${state.step===i?'active':''}" data-action="wizard-step" data-value="${i}" ${i>state.step?'disabled':''} ${i===state.step?'aria-current="step"':''}><span class="step-number">${i+1}</span>${name}</button>`).join('')}</div><div class="dialog-scroll">`;
 if(state.step===0)content+=`<div class="form-section"><h3>策略基础</h3>${formRow('策略名称 <span class="danger">*</span>',`<input id="rule-name" aria-label="策略名称" value="${esc(state.ruleName)}" placeholder="例如：工作设备分流">`)}${formRow('规则优先级',`<div class="row"><input id="rule-priority" aria-label="规则优先级" type="number" min="0" value="${state.priority}" style="max-width:160px"><label class="check"><input id="rule-enabled" type="checkbox" ${state.enabled?'checked':''}>启用此策略</label></div>`,'数字越小越先评估；不会隐式解决策略冲突。')}</div><div class="form-section"><h3>策略入口</h3><div class="choice-cards"><label class="choice-card"><input id="rule-ingress" type="checkbox" ${state.ingress?'checked':''}><span>LAN<span class="sub">接口列表 · 包含 bridge-lan</span></span></label><label class="choice-card"><input type="checkbox" disabled ${state.ingress?'checked':''}><span>bridge-lan<span class="sub">由 LAN 接口列表覆盖</span></span></label></div><p class="field-help">全部设备与排除模式需要选择入口。指定设备或手动地址时可以留空。</p></div><div class="form-section"><h3>来源范围</h3><div class="choice-cards">${[['all','入口内全部设备'],['selected','指定设备 / 地址'],['excluded','排除部分设备']].map(([id,name])=>`<label class="choice-card"><input type="radio" name="subject" value="${id}" ${state.subject===id?'checked':''}><span>${name}</span></label>`).join('')}</div>${state.subject!=='all'?`<div class="mini-grid" style="margin-top:14px">${['办公电脑','实验主机'].map(n=>`<label class="check"><input type="checkbox" checked>${n}</label>`).join('')}</div><textarea aria-label="手动来源地址" placeholder="手动 IP / CIDR，每行一个" style="width:100%;margin-top:10px"></textarea>`:''}</div>`;
 if(state.step===1)content+=`<div class="form-section"><div class="between"><h3>访问目标</h3>${button('+ 新建目标列表','nested-target','link')}</div><p class="field-help">选择可复用目标列表，或按应用选择域名 / IP 规则。</p>${formRow('目标列表','<label class="check"><input type="checkbox">开发服务域名 <span class="muted">· 12 条</span></label>')}<h3 style="margin-top:24px">应用规则</h3><div class="mini-grid">${['GitHub','Docker','Cloudflare','Google','YouTube','Microsoft'].map(n=>`<label class="choice-card"><input type="checkbox" name="app-target" value="${n}" ${state.targets.includes(n)?'checked':''}><span>${n}<span class="sub">域名规则</span></span><span class="spacer"></span><select aria-label="${n}规则类型" style="font-size:12px;min-height:28px"><option>域名</option><option>IP</option></select></label>`).join('')}</div><p class="field-help">所选应用：${state.targets.join('、')||'尚未选择'}</p></div>`;
 if(state.step===2)content+=`<div class="form-section"><h3>策略出口</h3>${['v4','v6'].map(f=>`<div style="margin-top:18px"><label class="check"><input type="checkbox" id="enable-${f}" ${state[f]?'checked':''}>启用 IPv${f.slice(1)}</label>${state[f]?`${formRow('策略 WAN 接口',`<select aria-label="IPv${f.slice(1)} WAN 接口" data-wan="${f}"><option ${state.wan==='pppoe-out1'?'selected':''}>pppoe-out1</option><option ${state.wan==='ether3'?'selected':''}>ether3</option><option>wireguard1</option><option ${state.wan==='下一跳网关'?'selected':''}>下一跳网关</option></select>`)}${formRow('下一跳网关',`<input id="gateway-${f}" aria-label="IPv${f.slice(1)} 下一跳网关" value="${esc(state.gateway)}" placeholder="${state.wan==='pppoe-out1'?'点对点接口无需填写':'填写网关 IP'}">`,state.wan==='pppoe-out1'?'当前选择 PPPoE 接口，可自动跟随接口。':'普通接口或下一跳模式需指定网关。')}`:''}</div>`).join('')}</div><details class="advanced"><summary>高级配置 · DNS、断线处理、路由表、NAT 与本机流量</summary><div>${formRow('断线处理',`<select id="failure" aria-label="断线处理"><option value="strict" ${state.failure==='strict'?'selected':''}>断线阻断</option><option value="fallback" ${state.failure==='fallback'?'selected':''}>回落 main</option><option value="existing" ${state.failure==='existing'?'selected':''}>沿用现有规则</option></select>`)}${formRow('DNS 上游',`<input id="dns" aria-label="DNS 上游" value="${esc(state.dns)}">`)}${formRow('Fake DNS 别名','<input aria-label="Fake DNS 别名" placeholder="自动分配">')}${formRow('路由表','<input aria-label="路由表" placeholder="自动创建专用表">')}${formRow('地址族断线覆盖','<select aria-label="地址族断线覆盖"><option>跟随全局设置</option><option>严格绑定</option><option>允许回落 main</option></select>')}${formRow('NAT 模式','<select aria-label="NAT 模式"><option>沿用现有 NAT</option><option>不建立 NAT</option><option>动态 masquerade</option></select>')}<label class="check"><input type="checkbox">包含 RouterOS 本机流量</label>${state.editing?'<label class="check"><input type="checkbox" checked>启用此出口</label>':''}</div></details>`;
 if(state.step===3)content+=`<div class="form-section"><h3>本次配置</h3><div class="review-meta">${kv('策略名称',esc(state.ruleName))}${kv('优先级',state.priority)}${kv('来源范围',state.subject==='all'?'LAN 全部':'指定设备 / 地址')}${kv('访问目标',esc(state.targets.join('、')))}${kv('策略出口',esc(state.wan))}${kv('地址族',[state.v4?'IPv4':'',state.v6?'IPv6':''].filter(Boolean).join(' / '))}</div><div class="notice">这里展示变更审阅界面的视觉。正式版本继续保留阻断项、地址族阻断、警告、计划过期检查及必选确认。</div></div><div class="form-section"><h3>变更清单 <span class="badge neutral">示例</span></h3><div class="panel" style="margin-top:16px"><div class="operation"><span class="muted">01</span>策略专用路由表<span class="badge">创建</span></div><div class="operation"><span class="muted">02</span>IPv4 策略路由<span class="badge">创建</span></div><div class="operation"><span class="muted">03</span>应用目标规则<span class="badge">复用</span></div><details><summary style="padding:14px 16px;color:var(--blue);cursor:pointer;font-size:12px">查看更多（剩余 2 条）</summary><div class="operation">IPv4 流量标记<span class="badge">创建</span></div><div class="operation">目标列表引用<span class="badge">建立引用</span></div></details></div><details class="advanced"><summary>计划详情</summary><div class="review-meta">${kv('计划类型','routing')}${kv('状态','ready · 示例')}${kv('目标修订','示例修订 4')}${kv('操作数量','5')}${kv('执行组','2')}${kv('计划哈希','示例，不生成真实哈希')}</div></details></div><label class="check"><input id="ack" type="checkbox" ${state.ack?'checked':''}>我已阅读本次示例变更</label>`;
 content+='</div>';
 const footer=button(state.step===0?'取消':state.step===3?'返回修改':'上一步',state.step===0?'close':'wizard-back')+`<button class="primary" data-action="${state.step===3?'apply-demo':'wizard-next'}" ${state.step===3&&!state.ack?'disabled':''}>${state.step===3?'确认并应用':state.step===2?'生成变更计划':'下一步'}</button>`;
 $('#dialog-content').innerHTML=dialogFrame(state.editing?'编辑路由策略':'新增路由策略',content,footer,'配置来源、访问目标与出口，确认变更计划后应用。此处仅为交互预览。');openDialog();
}
function simpleDialog(kind,value){
 state.dialog=kind;let title='',body='';
 if(kind==='target'){title='新增目标列表';body=formRow('名称','<input aria-label="目标列表名称" placeholder="例如：开发服务域名">')+formRow('类型','<select aria-label="目标类型"><option>域名</option><option>IP</option></select>')+formRow('来源','<select aria-label="目标来源" id="target-source"><option>手动内容</option><option>URL</option><option>上传文件</option></select>')+formRow('内容','<div id="target-source-input"><textarea aria-label="目标内容" placeholder="每行一条，例如 example.com"></textarea></div>')+formRow('校验',button('预览并校验','validate-target'));}
 if(kind==='access'){title='新增访问规则';body=formRow('规则名称','<input aria-label="访问规则名称" value="访客设备访问限制">')+formRow('来源','<select aria-label="访问来源"><option>指定设备 / 手动地址</option><option>全部设备</option></select>')+formRow('设备','<label class="check"><input type="checkbox" checked>移动设备</label>')+formRow('动作','<select aria-label="访问动作"><option>拒绝访问</option><option>允许访问</option></select>')+formRow('访问目标','<select aria-label="访问目标"><option>指定目标列表</option><option>互联网</option></select>')+formRow('目标列表','<label class="check"><input type="checkbox" checked>实验服务</label>')+formRow('启用规则','<label class="check"><input type="checkbox" checked>启用此规则</label>');}
 if(kind==='remark'){title='编辑终端';body=formRow('设备名称',`<input aria-label="终端名称" value="${esc(value||'办公电脑')}">`)+formRow('备注','<input aria-label="终端备注" placeholder="添加设备备注">');}
 if(kind==='delete'){title='删除路由策略';body=`<p style="line-height:1.9;padding:24px 0">确定删除“${esc(rules[Number(value)]?.name||'示例规则')}”？正式版本会同步清理对应规则。本次仅展示确认界面。</p>`;}
 $('#dialog-content').innerHTML=dialogFrame(title,`<div class="dialog-scroll">${body}</div>`,button('取消','close')+button(kind==='delete'?'删除':'保存',kind==='delete'?'demo-delete-close':'demo-save-close',kind==='delete'?'danger':'primary'));openDialog();
}
document.addEventListener('click',event=>{
 const control=event.target.closest('[data-action]');if(!control||control.disabled)return;const action=control.dataset.action,value=control.dataset.value;
 if(action==='nav'){navigate(submenus[value]?({monitor:'terminals',host:'routing',settings:'devices'}[value]):value);return;}
 if(titles[action]){navigate(action);return;}
 if(action==='mobile'){$('#app').classList.toggle('mobile-open');return;}
 if(action==='family'){state.family=value;render();return;}
 if(action==='traffic-window'){state.trafficWindow=value;render();return;}
 if(action==='target-filter'){state.targetFilter=value;render();return;}
 if(action==='sort-ip'){state.sort*=-1;$('#page').innerHTML=terminalPage();return;}
 if(action==='detail'){state.detail=value||control.textContent.trim();state.page='terminals';state.group='monitor';render();return;}
 if(action==='back-terminals'){state.detail=null;render();return;}
 if(action==='new-rule'||action==='edit-rule'){state.step=0;state.ack=false;state.editing=action==='edit-rule';if(state.editing){const r=rules[Number(value)];state.ruleName=r.name;state.priority=r.priority;state.enabled=r.enabled;state.targets=r.targets;state.wan=r.egress;}else{state.ruleName='';state.priority=100;state.enabled=true;}ruleWizard();return;}
 if(action==='toggle-rule'){const r=rules[Number(value)];r.enabled=!r.enabled;render();showToast('示例策略'+(r.enabled?'已启用':'已停用')+'，未连接 RouterOS。');return;}
 if(action==='delete-rule'){simpleDialog('delete',value);return;}
 if(action==='close'){closeDialog();return;}
 if(action==='wizard-next'){
  if(state.step===0&&!state.ruleName.trim()){showToast('请填写策略名称');$('#rule-name').focus();return;}
  if(state.step===0&&!state.ingress&&state.subject!=='selected'){showToast('全部设备与排除模式需要选择策略入口');return;}
  if(state.step===1&&!state.targets.length){showToast('请选择至少一项访问目标');return;}
  if(state.step===2&&!state.v4&&!state.v6){showToast('请选择至少一个地址族');return;}
  state.step++;ruleWizard();return;
 }
 if(action==='wizard-back'){state.step--;ruleWizard();return;}
 if(action==='wizard-step'){state.step=Number(value);ruleWizard();return;}
 if(action==='apply-demo'){closeDialog();showToast('已完成交互演示。未生成真实计划，未修改任何设备。');return;}
 if(action==='new-target'){simpleDialog('target');return;}
 if(action==='new-access'){simpleDialog('access');return;}
 if(action==='remark'){simpleDialog('remark',value);return;}
 if(action==='demo-save-close'||action==='demo-delete-close'){closeDialog();showToast('演示完成；未保存或删除任何真实数据。');return;}
 if(action==='validate-target'){showToast('校验结果示例：12 条有效规则，0 条错误。未实际解析或提交。');return;}
 if(action==='detail-tab'){showToast('此轮已绘制连接详情；应用统计和流量历史在正式改造时完整保留。');return;}
 if(action==='nested-target'){showToast('正式向导保留此处新建目标列表；预览可从“目标库”查看对应表单。');return;}
 if(action==='demo-toggle'){control.textContent=control.textContent==='停用'?'启用':'停用';showToast('仅切换示例按钮状态。');return;}
 showToast(action==='refresh'||action==='demo-refresh'?'预览使用固定示例数据，不请求设备。':'此按钮为视觉演示，未执行真实操作。');
});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='terminal-search'){state.termSearch=el.value;$('#page').innerHTML=terminalPage();}if(el.id==='fleet-search')document.querySelectorAll('[data-fleet-name]').forEach(row=>row.hidden=!row.dataset.fleetName.includes(el.value));if(el.id==='rule-name')state.ruleName=el.value;if(el.id==='rule-priority')state.priority=Number(el.value);if(el.id.startsWith('gateway-'))state.gateway=el.value;if(el.id==='dns')state.dns=el.value;});
document.addEventListener('change',event=>{const el=event.target;
 if(el.id==='layout'){state.layout=el.value;$('#app').classList.toggle('single',el.value==='single');}
 if(el.id==='online-filter'){state.visibility=el.value;$('#page').innerHTML=terminalPage();}
 if(el.id==='rule-enabled')state.enabled=el.checked;
 if(el.id==='rule-ingress'){state.ingress=el.checked;ruleWizard();}
 if(el.name==='subject'){state.subject=el.value;ruleWizard();}
 if(el.name==='app-target'){state.targets=el.checked?[...state.targets,el.value]:state.targets.filter(t=>t!==el.value);ruleWizard();}
 if(el.id==='enable-v4'||el.id==='enable-v6'){state[el.id.slice(7)]=el.checked;ruleWizard();}
 if(el.dataset.wan){state.wan=el.value;ruleWizard();}
 if(el.id==='failure')state.failure=el.value;
 if(el.id==='ack'){state.ack=el.checked;document.querySelector('[data-action=apply-demo]').disabled=!el.checked;}
 if(el.name==='appearance'){setTheme(el.value);}
 if(el.id==='target-source')$('#target-source-input').innerHTML=el.value==='手动内容'?'<textarea aria-label="目标内容" placeholder="每行一条"></textarea>':el.value==='URL'?'<input aria-label="订阅 URL" type="url" placeholder="https://example.com/list.txt">':'<input aria-label="上传目标文件" type="file">';
 if(el.id==='refresh'||el.id==='wan-summary'||el.closest('.device'))showToast('已选择示例选项；本预览不连接设备。');
});
function setTheme(theme){document.documentElement.dataset.theme=theme;$('#theme').textContent=theme==='dark'?'切换明亮':'切换深色';}
$('#theme').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
$('#editor').addEventListener('close',()=>state.dialog='');
render();
